### ISSUE TITLE
Click main image to advance gallery

### ISSUE THREAD

**Issue by bakman2** [bozz/flowgallery#2]
As subject, I am trying to implement a way to advance the gallery when the main image is shown. Currently only the thumbnails advance the gallery. 

In addition, I cannot seem to find the piece of code that enforces a border around the thumbnails, I want to have a border of 1px.

**Comment by bakman2** [comment]
Forgot the border part, found it.

btw; nice gallery :)

**Comment by bozz** [comment]
Hi bakman2, I just pushed a new version to github, it includes a config parameter "thumbPadding" for specifying border of thumbnails - this was hard coded before...

What do you mean with "advance the gallery when the main image is shown"? Do you mean some kind of automatic slide show effect? Or do you just want to trigger the animation with javascript?

Btw, I added a feature for navigation with arrow keys, also want to add support for the mouse wheel soon.

**Comment by bakman2** [comment]
I mean when the "big" picture is shown and one would click it: can it advance to the next image ? Currently only the thumbnails trigger an action (I would like to have both possible).

Thanks for your quick changes :) already implementing this in my new site.
