### ISSUE TITLE
Reinit gallery after ajax call

### ISSUE THREAD

**Issue by bakman2** [bozz/flowgallery#3]
I am trying to implement this gallery using ajax. Is there a way to reinitialize the plugin after an ajax call was performed ? 

Currently, when performing an ajax call, the gallery is shown, but it lost track of its position and its active image.

**Comment by bozz** [comment]
Do you want to reload it with new images after an ajax call or just initialize it after the call? In the second case you should initialize it after the ajax response comes back. For the first case, there is currently no built-in way to swap or dynamically add images - you would have to remove the gallery and initialize it again with the new images.

This is something I've been thinking about though, I would like to extend the gallery so that images can be dynamically loaded in the background as you are browsing - i.e. for viewing a flickr photo stream or something similar - where initially only a certain number are loaded directly and rest get loaded dynamically as you approach them.

**Comment by bakman2** [comment]
Indeed I was looking for the first case. I have tried to manipulate the active class and removing the gallery/bf-wrapper, I was almost there, but it didnt work properly as it doesn't return to the activeIndex (0). It should be possible you think ?

Or else, would it be possible to expose a reinit option that resets all vars (ie. like a initial start) ?

**Comment by bakman2** [comment]
I can show a demo:
_link removed_

try the first 2 thumbnails.

**Comment by bozz** [comment]
...for a quick workaround I would just remove the UL list of images when you want to load a new gallery and then add the new list of images - and then just call $('#list-id').flowGallery(...) on the new list each time. 

I will look into a way to improve this with some kine of reinit command that checks and goes through all images again.

**Comment by bakman2** [comment]
I tried this indeed, somehow the gallery seem to retain all values and doesn't get "reloaded" so to speak.

**Comment by bozz** [comment]
There was a problem with the way internal variables were initialized that didn't get reset properly when calling flowgallery again. I just submitted a fix for this ==> v0.6.1

Give it a try and let me know if it works for you.

**Comment by bakman2** [comment]
Man. You. Rock. 

Thanks so much for these quick changes! Works perfectly.

**Comment by bakman2** [comment]
Oh I spoke too soon ;)
Keyboard navigation lost track after an ajax call. Clicking works fine, when navigating using keyboard, it skips images

**Comment by bozz** [comment]
Thanks for all the testing ;-) Reinitializing the gallery was definitely not a use case that I had been testing...

The keyboard events were being executed multiple times after reinitialization, that was causing the skipping, should now be fixed ==> v0.6.2

(btw: I added a "forwardOnActiveClick" config parameter - this enables clicking on active image to move to next image)

**Comment by bakman2** [comment]
Really cool! Thanks again! All works - and extremely fast gallery. 

Now there is 1 thing leftover from me, sorry ;)
A cycle option, once reached the last image, if it could jump back/start over to the first image ?

**Comment by bakman2** [comment]
The caption doesn't get reset after reinitializing (sometimes it turns out smaller than the previous one and it becomes visible/stacked)

**Comment by bozz** [comment]
Cycling the gallery is not trivial - what should happen if there are only 2-3 images and a wide screen? Images would have to be duplicated multiple times to allow seemless cycling. It would probably be better to remove an image on one side and insert it on the other when reaching the "end" of the gallery. I'll give this some thought...

Regarding the caption bug - I'll have a look this evening...

**Comment by bozz** [comment]
I can't seem to reproduce the caption issue - I was looking at your demo page. Could you give some more details? What browser? Does this happen on your demo page when switching galleries?

**Comment by bakman2** [comment]
Sorry about the delay and my mistake, I didn't remove enough elements, causing multiple instances of bf-wrapper, fixed it.
